"""SQLModel ORM models for game.live_game_v1 API endpoint.

**Auto-generated from YAML schema mapping**

Endpoint: game
Method: live_game_v1
Version: 1.0

DO NOT EDIT THIS FILE MANUALLY!
Regenerate using: uv run python -m mlb_data_platform.schema.orm_generator

These models use SQLModel (SQLAlchemy 2.0 + Pydantic) for:
- Type-safe database access
- Pydantic validation
- Async support
- Alembic migrations
"""

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Optional

from sqlalchemy import BigInteger, Boolean, Date, DateTime, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, SQLModel



class BaseModel(SQLModel):
    """Base model for all ORM classes."""

    class Config:
        """Pydantic config."""

        arbitrary_types_allowed = True
        from_attributes = True

class LiveGameMetadata(BaseModel, table=True):
    """Core game information: teams, venue, status, timing, weather"""

    __tablename__ = "live_game_metadata"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False, description="Unique game identifier")  # $.gamePk
    game_type: Optional[str] = Field(sa_type=String(5), description="R=Regular, P=Playoff, W=World Series", default=None)  # $.gameData.game.type
    season: Optional[str] = Field(sa_type=String(4), default=None)  # $.gameData.game.season
    season_type: Optional[str] = Field(sa_type=String(20), default=None)  # $.gameData.game.seasonDisplay
    game_date: date = Field(sa_type=Date, nullable=False)  # $.gameData.datetime.officialDate
    game_datetime: Optional[datetime] = Field(sa_type=DateTime, default=None)  # $.gameData.datetime.dateTime
    day_night: Optional[str] = Field(sa_type=String(10), default=None)  # $.gameData.datetime.dayNight
    time_zone: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.datetime.time
    venue_id: Optional[int] = Field(sa_type=Integer, default=None)  # $.gameData.venue.id
    venue_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.gameData.venue.name
    home_team_id: Optional[int] = Field(sa_type=Integer, default=None)  # $.gameData.teams.home.id
    home_team_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.gameData.teams.home.name
    away_team_id: Optional[int] = Field(sa_type=Integer, default=None)  # $.gameData.teams.away.id
    away_team_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.gameData.teams.away.name
    abstract_game_state: Optional[str] = Field(sa_type=String(20), description="Preview, Live, Final", default=None)  # $.gameData.status.abstractGameState
    coded_game_state: Optional[str] = Field(sa_type=String(5), default=None)  # $.gameData.status.codedGameState
    detailed_state: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.status.detailedState
    status_code: Optional[str] = Field(sa_type=String(5), default=None)  # $.gameData.status.statusCode
    reason: Optional[str] = Field(sa_type=Text, default=None)  # $.gameData.status.reason
    home_score: Optional[int] = Field(sa_type=Integer, default=None)  # $.liveData.linescore.teams.home.runs
    away_score: Optional[int] = Field(sa_type=Integer, default=None)  # $.liveData.linescore.teams.away.runs
    weather_condition: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.weather.condition
    weather_temp: Optional[int] = Field(sa_type=Integer, default=None)  # $.gameData.weather.temp
    weather_wind: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.weather.wind
    source_raw_id: Optional[int] = Field(sa_type=BigInteger, description="FK to game.live_game_v1.id", default=None)
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)
    transform_timestamp: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameLinescoreInnings(BaseModel, table=True):
    """Inning-by-inning scoring breakdown"""

    __tablename__ = "live_game_linescore_innings"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.gamePk
    inning_number: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $.num
    half_inning: str = Field(sa_type=String(10), primary_key=True, description="Top or Bottom")  # $.ordinalNum
    home_runs: Optional[int] = Field(sa_type=Integer, default=None)  # $.home.runs
    away_runs: Optional[int] = Field(sa_type=Integer, default=None)  # $.away.runs
    home_hits: Optional[int] = Field(sa_type=Integer, default=None)  # $.home.hits
    away_hits: Optional[int] = Field(sa_type=Integer, default=None)  # $.away.hits
    home_errors: Optional[int] = Field(sa_type=Integer, default=None)  # $.home.errors
    away_errors: Optional[int] = Field(sa_type=Integer, default=None)  # $.away.errors
    home_left_on_base: Optional[int] = Field(sa_type=Integer, default=None)  # $.home.leftOnBase
    away_left_on_base: Optional[int] = Field(sa_type=Integer, default=None)  # $.away.leftOnBase
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGamePlayers(BaseModel, table=True):
    """All players involved in the game (51+ per game)"""

    __tablename__ = "live_game_players"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.gamePk
    player_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $.id
    full_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.fullName
    first_name: Optional[str] = Field(sa_type=String(50), default=None)  # $.firstName
    last_name: Optional[str] = Field(sa_type=String(50), default=None)  # $.lastName
    primary_number: Optional[str] = Field(sa_type=String(5), default=None)  # $.primaryNumber
    birth_date: Optional[date] = Field(sa_type=Date, default=None)  # $.birthDate
    current_age: Optional[int] = Field(sa_type=Integer, default=None)  # $.currentAge
    birth_city: Optional[str] = Field(sa_type=String(100), default=None)  # $.birthCity
    birth_country: Optional[str] = Field(sa_type=String(100), default=None)  # $.birthCountry
    height: Optional[str] = Field(sa_type=String(10), default=None)  # $.height
    weight: Optional[int] = Field(sa_type=Integer, default=None)  # $.weight
    bats: Optional[str] = Field(sa_type=String(1), default=None)  # $.batSide.code
    throws: Optional[str] = Field(sa_type=String(1), default=None)  # $.pitchHand.code
    primary_position_code: Optional[str] = Field(sa_type=String(2), default=None)  # $.primaryPosition.code
    primary_position_name: Optional[str] = Field(sa_type=String(50), default=None)  # $.primaryPosition.name
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGamePlays(BaseModel, table=True):
    """All plays in the game (at-bats, ~75 per game)"""

    __tablename__ = "live_game_plays"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.gamePk
    play_id: str = Field(sa_type=String(50), primary_key=True, nullable=False)  # $.playId
    at_bat_index: Optional[int] = Field(sa_type=Integer, default=None)  # $.atBatIndex
    inning: Optional[int] = Field(sa_type=Integer, default=None)  # $.about.inning
    half_inning: Optional[str] = Field(sa_type=String(10), default=None)  # $.about.halfInning
    is_top_inning: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.about.isTopInning
    outs_before: Optional[int] = Field(sa_type=Integer, default=None)  # $.about.startTime
    outs_after: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.outs
    event_type: Optional[str] = Field(sa_type=String(50), default=None)  # $.result.eventType
    event: Optional[str] = Field(sa_type=String(100), default=None)  # $.result.event
    description: Optional[str] = Field(sa_type=Text, default=None)  # $.result.description
    rbi: Optional[int] = Field(sa_type=Integer, default=None)  # $.result.rbi
    away_score: Optional[int] = Field(sa_type=Integer, default=None)  # $.result.awayScore
    home_score: Optional[int] = Field(sa_type=Integer, default=None)  # $.result.homeScore
    batter_id: Optional[int] = Field(sa_type=Integer, default=None)  # $.matchup.batter.id
    pitcher_id: Optional[int] = Field(sa_type=Integer, default=None)  # $.matchup.pitcher.id
    batter_side: Optional[str] = Field(sa_type=String(1), default=None)  # $.matchup.batSide.code
    pitcher_hand: Optional[str] = Field(sa_type=String(1), default=None)  # $.matchup.pitchHand.code
    balls: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.balls
    strikes: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.strikes
    start_time: Optional[datetime] = Field(sa_type=DateTime, default=None)  # $.about.startTime
    end_time: Optional[datetime] = Field(sa_type=DateTime, default=None)  # $.about.endTime
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGamePitchEvents(BaseModel, table=True):
    """Every pitch thrown in the game (~250 per game) - PITCH EVENTS ONLY (isPitch=true)"""

    __tablename__ = "live_game_pitch_events"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.gamePk
    play_id: str = Field(sa_type=String(50), primary_key=True, nullable=False)  # parent.playId
    pitch_number: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $.pitchNumber
    action_index: Optional[int] = Field(sa_type=Integer, default=None)  # $.index
    pitch_type_code: Optional[str] = Field(sa_type=String(10), default=None)  # $.details.type.code
    pitch_type_description: Optional[str] = Field(sa_type=String(100), default=None)  # $.details.type.description
    pitch_call_code: Optional[str] = Field(sa_type=String(5), default=None)  # $.details.call.code
    pitch_call_description: Optional[str] = Field(sa_type=String(50), default=None)  # $.details.call.description
    is_strike: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.details.isStrike
    is_ball: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.details.isBall
    is_in_play: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.details.isInPlay
    start_speed: Optional[Decimal] = Field(sa_type=Numeric(5,2), description="MPH", default=None)  # $.pitchData.startSpeed
    end_speed: Optional[Decimal] = Field(sa_type=Numeric(5,2), default=None)  # $.pitchData.endSpeed
    strike_zone_top: Optional[Decimal] = Field(sa_type=Numeric(5,2), default=None)  # $.pitchData.strikeZoneTop
    strike_zone_bottom: Optional[Decimal] = Field(sa_type=Numeric(5,2), default=None)  # $.pitchData.strikeZoneBottom
    coordinates_x: Optional[Decimal] = Field(sa_type=Numeric(6,2), default=None)  # $.pitchData.coordinates.x
    coordinates_y: Optional[Decimal] = Field(sa_type=Numeric(6,2), default=None)  # $.pitchData.coordinates.y
    break_angle: Optional[Decimal] = Field(sa_type=Numeric(5,2), default=None)  # $.pitchData.breaks.breakAngle
    break_length: Optional[Decimal] = Field(sa_type=Numeric(5,2), default=None)  # $.pitchData.breaks.breakLength
    break_y: Optional[Decimal] = Field(sa_type=Numeric(5,2), default=None)  # $.pitchData.breaks.breakY
    spin_rate: Optional[int] = Field(sa_type=Integer, default=None)  # $.pitchData.breaks.spinRate
    spin_direction: Optional[int] = Field(sa_type=Integer, default=None)  # $.pitchData.breaks.spinDirection
    balls_before: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.balls
    strikes_before: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.strikes
    outs: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.outs
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGamePlayActions(BaseModel, table=True):
    """Non-pitch events: substitutions, pickoffs, mound visits, reviews (~10-20 per game) - NON-PITCH EVENTS ONLY (isPitch=false)"""

    __tablename__ = "live_game_play_actions"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.gamePk
    play_id: str = Field(sa_type=String(50), primary_key=True, nullable=False)  # parent.playId
    action_index: int = Field(sa_type=Integer, primary_key=True, nullable=False, description="Index of action within play")  # $.index
    action_type: Optional[str] = Field(sa_type=String(50), description="substitution, pickoff, caught_stealing, stolen_base, etc.", default=None)  # $.type
    event_type: Optional[str] = Field(sa_type=String(50), default=None)  # $.details.eventType
    description: Optional[str] = Field(sa_type=Text, default=None)  # $.details.description
    is_substitution: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.isSubstitution
    player_out_id: Optional[int] = Field(sa_type=Integer, description="Player being replaced (for substitutions)", default=None)  # $.details.fromId
    player_in_id: Optional[int] = Field(sa_type=Integer, description="Player entering game (for substitutions)", default=None)  # $.details.toId
    position: Optional[str] = Field(sa_type=String(10), description="Position code for substitution", default=None)  # $.position.code
    batting_order: Optional[int] = Field(sa_type=Integer, description="Batting order position", default=None)  # $.battingOrder
    start_time: Optional[datetime] = Field(sa_type=DateTime, default=None)  # $.startTime
    end_time: Optional[datetime] = Field(sa_type=DateTime, default=None)  # $.endTime
    balls: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.balls
    strikes: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.strikes
    outs: Optional[int] = Field(sa_type=Integer, default=None)  # $.count.outs
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameFieldingCredits(BaseModel, table=True):
    """Defensive credits for each play (putouts, assists, errors)"""

    __tablename__ = "live_game_fielding_credits"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.gamePk
    play_id: str = Field(sa_type=String(50), primary_key=True, nullable=False)  # parent.parent.playId
    event_index: int = Field(sa_type=Integer, primary_key=True, nullable=False, description="Index of event within play")  # parent.index
    credit_index: int = Field(sa_type=Integer, primary_key=True, nullable=False, description="Index of credit within event")
    player_id: int = Field(sa_type=Integer, nullable=False)  # $.player.id
    player_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.player.link
    position_code: Optional[str] = Field(sa_type=String(5), description="P, C, 1B, 2B, 3B, SS, LF, CF, RF", default=None)  # $.position.code
    position_name: Optional[str] = Field(sa_type=String(50), default=None)  # $.position.name
    credit_type: Optional[str] = Field(sa_type=String(20), description="f_putout, f_assist, f_error, f_fielded_ball, etc.", default=None)  # $.credit
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameRunners(BaseModel, table=True):
    """Base runners and their movements for each play"""

    __tablename__ = "live_game_runners"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.gamePk
    play_id: str = Field(sa_type=String(50), primary_key=True, nullable=False)  # parent.playId
    runner_index: int = Field(sa_type=Integer, primary_key=True, nullable=False, description="Index of runner (0-2 for bases)")  # $.movement.originBase
    runner_id: Optional[int] = Field(sa_type=Integer, default=None)  # $.details.runner.id
    start_base: Optional[str] = Field(sa_type=String(5), description="Base runner started on (1B, 2B, 3B, score)", default=None)  # $.movement.start
    end_base: Optional[str] = Field(sa_type=String(5), default=None)  # $.movement.end
    is_out: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.movement.isOut
    out_number: Optional[int] = Field(sa_type=Integer, default=None)  # $.movement.outNumber
    event_type: Optional[str] = Field(sa_type=String(50), default=None)  # $.details.event
    movement_reason: Optional[str] = Field(sa_type=String(100), default=None)  # $.details.movementReason
    is_scoring_event: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.details.isScoringEvent
    rbi: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.details.rbi
    earned_run: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.details.earned
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameScoringPlays(BaseModel, table=True):
    """Plays that resulted in runs scored"""

    __tablename__ = "live_game_scoring_plays"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)
    play_index: int = Field(sa_type=Integer, primary_key=True, nullable=False, description="Index from scoringPlays array")
    inning: Optional[int] = Field(sa_type=Integer, default=None)
    half_inning: Optional[str] = Field(sa_type=String(10), default=None)
    description: Optional[str] = Field(sa_type=Text, default=None)
    runs_scored: Optional[int] = Field(sa_type=Integer, default=None)
    away_score_after: Optional[int] = Field(sa_type=Integer, default=None)
    home_score_after: Optional[int] = Field(sa_type=Integer, default=None)
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameHomeBattingOrder(BaseModel, table=True):
    """Home team batting order"""

    __tablename__ = "live_game_home_batting_order"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    batting_position: int = Field(sa_type=Integer, primary_key=True, nullable=False)
    player_id: int = Field(sa_type=Integer, nullable=False, description="Player ID from battingOrder array element")  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameAwayBattingOrder(BaseModel, table=True):
    """Away team batting order"""

    __tablename__ = "live_game_away_batting_order"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    batting_position: int = Field(sa_type=Integer, primary_key=True, nullable=False)
    player_id: int = Field(sa_type=Integer, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameHomePitchers(BaseModel, table=True):
    """Home team pitchers used in game"""

    __tablename__ = "live_game_home_pitchers"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    pitcher_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameAwayPitchers(BaseModel, table=True):
    """Away team pitchers used in game"""

    __tablename__ = "live_game_away_pitchers"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    pitcher_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameHomeBench(BaseModel, table=True):
    """Home team bench players"""

    __tablename__ = "live_game_home_bench"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    player_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameAwayBench(BaseModel, table=True):
    """Away team bench players"""

    __tablename__ = "live_game_away_bench"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    player_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameHomeBullpen(BaseModel, table=True):
    """Home team bullpen (available relief pitchers)"""

    __tablename__ = "live_game_home_bullpen"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    pitcher_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameAwayBullpen(BaseModel, table=True):
    """Away team bullpen (available relief pitchers)"""

    __tablename__ = "live_game_away_bullpen"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.parent.parent.gamePk
    pitcher_id: int = Field(sa_type=Integer, primary_key=True, nullable=False)  # $
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameUmpires(BaseModel, table=True):
    """Umpiring crew for the game"""

    __tablename__ = "live_game_umpires"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)  # parent.parent.parent.gamePk
    umpire_id: int = Field(sa_type=Integer, nullable=False)  # $.official.id
    umpire_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.official.fullName
    umpire_position: str = Field(sa_type=String(20), primary_key=True, nullable=False, description="Home Plate, First Base, Second Base, Third Base")  # $.officialType
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)

class LiveGameVenueDetails(BaseModel, table=True):
    """Detailed venue information for the game"""

    __tablename__ = "live_game_venue_details"
    __table_args__ = {"schema": "game"}

    game_pk: int = Field(sa_type=BigInteger, primary_key=True, nullable=False)
    venue_id: int = Field(sa_type=Integer, nullable=False)  # $.gameData.venue.id
    venue_name: Optional[str] = Field(sa_type=String(100), default=None)  # $.gameData.venue.name
    city: Optional[str] = Field(sa_type=String(100), default=None)  # $.gameData.venue.location.city
    state: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.venue.location.state
    country: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.venue.location.country
    timezone_id: Optional[str] = Field(sa_type=String(50), default=None)  # $.gameData.venue.timeZone.id
    timezone_offset: Optional[int] = Field(sa_type=Integer, description="Offset from UTC in hours", default=None)  # $.gameData.venue.timeZone.offset
    field_info: Optional[dict] = Field(sa_type=JSONB, description="Field dimensions, surface type, roof type, etc.", default=None)  # $.gameData.venue.fieldInfo
    is_active: Optional[bool] = Field(sa_type=Boolean, default=None)  # $.gameData.venue.active
    season: Optional[str] = Field(sa_type=String(4), default=None)  # $.gameData.venue.season
    source_captured_at: Optional[datetime] = Field(sa_type=DateTime, default=None)


# End of auto-generated models

