terraform {
  required_version = ">= 1.5.0"

  # Backend configuration is generated by setup.sh
  # Creates backend.tf with your S3 settings
  # Run: ./setup.sh to configure

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

provider "github" {
  owner = var.github_owner
  # Token should be set via GITHUB_TOKEN environment variable
}

# Import existing repository (created via gh CLI)
import {
  to = github_repository.repo
  id = "mlb_statsapi_data_platform"
}

# Repository - now managed by Terraform
resource "github_repository" "repo" {
  name        = var.github_repository
  description = "Kubernetes-native data platform for MLB Stats API with PySpark ETL, PostgreSQL data mart, and comprehensive BDD testing"

  visibility = "public"

  has_issues      = true
  has_discussions = false
  has_projects    = true
  has_wiki        = false

  # Enable vulnerability alerts and automated security fixes
  vulnerability_alerts   = true
  delete_branch_on_merge = true

  # Allow squash merging (recommended for feature branches)
  allow_squash_merge = true
  allow_merge_commit = true
  allow_rebase_merge = true

  # Topics/tags for discoverability
  topics = [
    "mlb",
    "baseball",
    "data-platform",
    "pyspark",
    "etl",
    "kubernetes",
    "postgresql",
    "bdd-testing",
    "behave",
    "data-engineering",
    "kappa-architecture",
    "mlb-stats",
    "sports-data",
  ]

  lifecycle {
    prevent_destroy = true
  }
}

# Set default branch to main
resource "github_branch_default" "default" {
  repository = github_repository.repo.name
  branch     = "main"
}

# Branch protection for main (production)
resource "github_branch_protection" "main" {
  repository_id = github_repository.repo.node_id
  pattern       = "main"

  enforce_admins                  = false # Allow admins to bypass in emergencies
  require_signed_commits          = false
  required_linear_history         = false
  require_conversation_resolution = true

  # Require pull request reviews
  required_pull_request_reviews {
    dismiss_stale_reviews           = true
    require_code_owner_reviews      = false # Set to true when CODEOWNERS is added
    required_approving_review_count = 1
    restrict_dismissals             = false
  }

  allows_force_pushes = false
  allows_deletions    = false
}

# Issue labels for better organization
resource "github_issue_label" "bug" {
  repository  = github_repository.repo.name
  name        = "bug"
  color       = "d73a4a"
  description = "Something isn't working"
}

resource "github_issue_label" "enhancement" {
  repository  = github_repository.repo.name
  name        = "enhancement"
  color       = "a2eeef"
  description = "New feature or request"
}

resource "github_issue_label" "documentation" {
  repository  = github_repository.repo.name
  name        = "documentation"
  color       = "0075ca"
  description = "Improvements or additions to documentation"
}

resource "github_issue_label" "testing" {
  repository  = github_repository.repo.name
  name        = "testing"
  color       = "fbca04"
  description = "Related to testing"
}

resource "github_issue_label" "bdd" {
  repository  = github_repository.repo.name
  name        = "bdd"
  color       = "1d76db"
  description = "Behavior-driven development tests"
}

resource "github_issue_label" "transformation" {
  repository  = github_repository.repo.name
  name        = "transformation"
  color       = "c5def5"
  description = "Data transformation layer"
}

resource "github_issue_label" "ingestion" {
  repository  = github_repository.repo.name
  name        = "ingestion"
  color       = "5319e7"
  description = "Data ingestion layer"
}

# Outputs for documentation
output "repository" {
  value = {
    name           = github_repository.repo.name
    full_name      = github_repository.repo.full_name
    html_url       = github_repository.repo.html_url
    default_branch = github_branch_default.default.branch
    branches = {
      main = "protected, requires PR approval"
    }
    managed_by = "Terraform with manual backend"
  }
}
